version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
    - 3306:3306


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - MEMORY_LIMIT=512M
      - UPLOAD_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=3600
      - PMA_HOST=db